# Generated by Django 3.2.5 on 2021-07-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receitas_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
